// Known EMV tags (top level)
const TAG_LABELS = {
  "00": "Payload Format Indicator",
  "01": "Point of Initiation Method",
  "26": "Merchant Account Information (Template)",
  "27": "Merchant Account Information (Template)",
  "28": "Merchant Account Information (Template)",
  "29": "Merchant Account Information (Template)",
  "30": "Merchant Account Information (Template)",
  "31": "Merchant Account Information (Template)",
  "32": "Merchant Account Information (Template)",
  "33": "Merchant Account Information (Template)",
  "34": "Merchant Account Information (Template)",
  "35": "Merchant Account Information (Template)",
  "36": "Merchant Account Information (Template)",
  "37": "Merchant Account Information (Template)",
  "38": "Merchant Account Information (Template)",
  "39": "Merchant Account Information (Template)",
  "40": "Merchant Account Information (Template)",
  "41": "Merchant Account Information (Template)",
  "42": "Merchant Account Information (Template)",
  "43": "Merchant Account Information (Template)",
  "44": "Merchant Account Information (Template)",
  "45": "Merchant Account Information (Template)",
  "46": "Merchant Account Information (Template)",
  "47": "Merchant Account Information (Template)",
  "48": "Merchant Account Information (Template)",
  "49": "Merchant Account Information (Template)",
  "50": "Merchant Account Information (Template)",
  "51": "Merchant Account Information (Template)",

  "52": "Merchant Category Code",
  "53": "Transaction Currency",
  "54": "Transaction Amount",
  "55": "Tip or Convenience Indicator",
  "56": "Value of Convenience Fee Fixed",
  "57": "Value of Convenience Fee Percentage",
  "58": "Country Code",
  "59": "Merchant Name",
  "60": "Merchant City",
  "61": "Postal Code",
  "62": "Additional Data Field Template",
  "63": "CRC",

  // Common sub-tags inside templates
  sub_00: "Globally Unique Identifier (GUI)",
  sub_01: "Merchant Account / Bank Code / Identifier",
  sub_02: "Account / Wallet / Phone Number",
  sub_03: "Additional Info",
};
